#!/bin/bash
#Install pure python modules in the directory
python3 -m pip install -r ./requirements.txt -t .

# clone cryptos module from github
mkdir tmp
pushd ./tmp
git clone https://github.com/Alcofribas4/pybitcointools.git
pushd ./pybitcointools
cp -r cryptos ../..
popd
popd
rm -rf ./tmp

# clone ethereum-lists/chains module from github
git clone https://github.com/ethereum-lists/chains.git

# In the chains folder, remove all files & folders except for _data folder:
find ./chains -mindepth 1 ! -regex '^./chains/_data\(/.*\)?' -delete
