#!/bin/bash
#Install pure python modules in the directory
python3 -m pip install --upgrade -r ./requirements.txt -t .

# remove pycryptodome (Crypto) package as it causes issues with pbkdf2
rm -rf ./Crypto
rm -rf ./pycryptodome-*

# clone cryptos module from github
mkdir tmp
pushd ./tmp
git clone https://github.com/Alcofribas4/pybitcointools.git
pushd ./pybitcointools
cp -r cryptos ../..
popd
popd
rm -rf ./tmp

# remove chains directory before downloading it again
rm -rf ./chains
# clone ethereum-lists/chains module from github
git clone https://github.com/ethereum-lists/chains.git
# In the chains folder, remove all files & folders except for _data/chains folder:
find ./chains -mindepth 1 ! -regex '^./chains/_data/chains\(/.*\)?' -delete
